name: Build Next.js App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build
        
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r .next deployment/
          cp -r public deployment/ || true
          cp package.json deployment/
          cp package-lock.json deployment/ || true
          cp next.config.js deployment/ || true
          cp start.js deployment/
          
      - name: Create ZIP archive
        run: |
          cd deployment
          zip -r ../woocommerce-orders-build.zip .
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: woocommerce-orders-build
          path: woocommerce-orders-build.zip
